peer:
  my_account: eos.docker
  api_address: http://localhost:8888
  secret_p2p_address: localhost:9876
  block_signing_private_key_path: ./privkey-GDW5CV.key

network:
  seed_discovery_url: https://abourget.keybase.pub/testnet-docker.yaml
  cache_path: .cache
